name: Publish release to GitHub
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Version bump"]
    branches: [master]
    types:
      - completed
jobs:
  version-bump:
    name: Release to github releases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo ::set-env name=pkg_version::$(awk '/version/{gsub(/("|",)/,"",$2);print $2}' package.json)
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ env.pkg_version }}
          release_name: ${{ env.pkg_version }}
          body: |
            -
          draft: true
          prerelease: false
